version: '3.1'

services:
  api:
    image: #{DOCKER_REGISTRY}/#{Octopus.Action.Package[CoachMeApi].PackageId}:#{Octopus.Action.Package[CoachMeApi].PackageVersion}
    environment:
      - DOTNET_ENVIRONMENT=#{ENVIRONMENT}
      - GOOGLE_APPLICATION_CREDENTIALS=Oomssport Training-a192e0fcd823.json
    networks:
      - edge
    deploy:
      placement:
          constraints:
            - "node.role==worker"
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.coachme-api.loadbalancer.server.port=80"
        - "traefik.http.middlewares.#{SubDomain}-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.#{SubDomain}-http.entrypoints=web"
        - "traefik.http.routers.#{SubDomain}-http.middlewares=#{SubDomain}-https-redirect@docker"
        - "traefik.http.routers.#{SubDomain}-http.rule=Host(`#{HostUrl}`)"
        - "traefik.http.routers.#{SubDomain}-https.entrypoints=websecure"
        - "traefik.http.routers.#{SubDomain}-https.rule=Host(`#{HostUrl}`)"
        - "traefik.http.routers.#{SubDomain}-https.tls.certresolver=myresolver" 
      
networks:
  edge:
    external:
      name: edge
